[project]
name = "vep-comparisons"
version = "0.1.0"
description = "Workflows for curating and comparing variant effect predictions"
readme = "README.md"
authors = [
    { name = "Anonymous", email = "user@example.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "jupyter>=1.1.1",
    "marimo>=0.23.16",
    "matplotlib>=3.11.1",
    "nbformat>=5.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "polars>=1.43.2",
    "pyarrow>=25.0.1",
    "pybigwig>=0.3.25",
    "pysam>=0.24.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "torch==2.6.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
protein-models = [
    "esm==3.2.3",
    "transformers==4.48.1",
]
ntv3 = [
    "transformers @ git+https://github.com/huggingface/transformers.git@v4.55.4",
]

[project.scripts]
vep-comparisons = "vep_comparisons.cli:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
environments = ["sys_platform == 'linux'"]
conflicts = [
    [
        { extra = "protein-models" },
        { extra = "ntv3" },
    ],
]
